---
# tasks file for abyres.hdp-pgsql
- name: install postgresql
  yum: name=postgresql-server,postgresql,python-psycopg2 state=latest

- name: create postgresql superuser
  postgresql_user: name=root password={{ superuser_password }} role_attr_flags=SUPERUSER
  become: true
  become_user: postgres

- name: create hive metastore db
  postgresql_db: name=hive encoding='UTF-8'
  become: true
  become_user: postgres

- name: create hive metastore user
  postgresql_user: db=hive name=hive password={{ hive_db_password }} priv=ALL
  become: true
  become_user: postgres

- name: create oozie db
  postgresql_db: name=oozie encoding='UTF-8'
  become: true
  become_user: postgres

- name: create oozie user
  postgresql_user: db=oozie name=oozie password={{ oozie_db_password }} priv=ALL
  become: true
  become_user: postgres

- name: create ranger db
  postgresql_db: name=ranger encoding='UTF-8'
  become: true
  become_user: postgres

- name: create rangeradmin user
  postgresql_user: db=ranger name=rangeradmin password={{ ranger_db_password }} priv=ALL
  become: true
  become_user: postgres

- name: create ranger_audit db
  postgresql_db: name=ranger_audit encoding='UTF-8'
  become: true
  become_user: postgres

- name: create rangerlogger user
  postgresql_user: db=ranger_audit name=rangerlogger password={{ rangeraudit_db_password }} priv=ALL
  become: true
  become_user: postgres


- name: create rangerkms db
  postgresql_db: name=rangerkms encoding='UTF-8'
  become: true
  become_user: postgres

- name: create rangerkms user
  postgresql_user: db=rangerkms name=rangerkms password={{ rangerkms_db_password }} priv=ALL
  become: true
  become_user: postgres
