---
# tasks file for abyres.hdp-update-mirror

- name: download Ambari repo
  get_url: url={{ ambari_tarball_url }} dest=/opt/mirror/{{ ambari_tarball_url | basename }} sha256sum={{ ambari_tarball_checksum }}
  when: ambari_download

- name: download HDP repo
  get_url: url={{ hdp_tarball_url }} dest=/opt/mirror/{{ hdp_tarball_url | basename }} sha256sum={{ hdp_tarball_checksum }}
  when: hdp_download

- name: download HDP-UTILS repo
  get_url: url={{ hdputils_tarball_url }} dest=/opt/mirror/{{ hdputils_tarball_url | basename }} sha256sum={{ hdputils_tarball_checksum }}
  when: utils_download

- name: extract Ambari repo
  unarchive: src=/opt/mirror/{{ ambari_tarball_url | basename }} dest=/var/www/html/mirror/ copy=no creates=/var/www/html/mirror/AMBARI-2.2.1.1
  when: ambari_download

- name: extract HDP repo
  unarchive: src=/opt/mirror/{{ hdp_tarball_url | basename }} dest=/var/www/html/mirror/ copy=no creates=/var/www/html/mirror/HDP
  when: hdp_download

- name: extract HDP-UTILS repo
  unarchive: src=/opt/mirror/{{ hdputils_tarball_url | basename }} dest=/var/www/html/mirror/ copy=no creates=/var/www/html/mirror/HDP-UTILS-1.1.0.20
  when: utils_download
